title: Artwork Categorization
description: Abdullah Ahmed, Alec Albrecht, Carlos Hernandez, Ankita Somu, Sanjana Srinivasan 
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist
baseurl: /ML-Project-Group-77